name: Generate and Save XML
on:
  push:
  repository_dispatch:
    types: [generate-xml]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.0"

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: |
          go run .

      - name: Commit immich_kiosk.xml
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add immich_kiosk.xml
          git commit -m "Update immich_kiosk.xml" || echo "No changes to commit"
          git push
